### ISSUE TITLE
MBSnapshot is implemented in both MobileBackup and MapboxStatic

### ISSUE THREAD

**Issue by dimazen** [mapbox/MapboxStatic.swift#105] opened 2020-07-24 14:55 UTC
Hello, Mapbox team! 
I've encountered a following issue on iOS 13.5:

objc[5073]: Class MBSnapshot is implemented in both /System/Library/PrivateFrameworks/MobileBackup.framework/MobileBackup (0x1f4d85af8) and /private/var/[redacted]/Frameworks/MapboxStatic.framework/MapboxStatic (0x109100ee8). One of the two will be used. Which one is undefined.

Can you please rename your class somehow to have either a three-letter prefix or a different name? From the Guidelines looks like that Apple has reserved a two-letter prefixes for their own frameworks :/

**Comment by Frederikdam** [comment] 2020-09-08 15:06
👍

**Comment by 1ec5** [comment] 2020-11-09 19:47
Duplicate of #86.

**Closed by 1ec5** 2020-11-09 19:47 UTC
